Mobilebranch
mwakiogeofrey/MICROVERSE-MOBILE-PORTFOLIO pull request #1
Opened 2023-01-17 11:08 UTC by mwakiogeofrey

2023-01-17 11:33 UTC, didierganthier reviewed
Hi @mwakiogeofrey ,

While you put in a lot of hard work in this project, unfortunately, I cannot proceed with the review of your code.

<img src="https://media.giphy.com/media/d2lcHJTG5Tscg/giphy.gif" />

## Invalid Code Review Request 🚫

- You have submitted a project without a descriptive PR:
  - Pull Request should have a descriptive title telling you what changes are inside.
  - Pull Request should have a short summary describing introduced changes in more detail

Your Code Review Request will be marked as invalid in your Dashboard, but don't worry you can always try again! 💪

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

--------

_Invalid Code Review Request **does not count** towards the code reviews limit._

2023-01-17 16:09 UTC, mwakiogeofrey commented
### Mobile portfolio project 
The project is about making the final part of mobile portfolio and making sure there is no linters error.

2023-01-17 16:16 UTC, christianbiring1 reviewed
Hi @mwakiogeofrey , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request :heavy_multiplication_x: 
![Invalid](https://user-images.githubusercontent.com/97100091/212952573-54995908-a7e0-4280-b7df-313f701b15ee.gif)


You have submitted a project, that 
- [ ] without a descriptive PR:
- [ ] should have a descriptive title telling you what changes are inside.
- [ ] Pull Request should have a short summary describing introduced changes in more detail

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-17 17:42 UTC, jasonfelice requested changes
Hi  @mwakiogeofrey, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
No Linter errors✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 17:42 UTC, jasonfelice commented on index.html
> +        </header>
- [ ] Kindly make sure you are using the right font and complying with the Figma design.

## Figma Design
![image](https://user-images.githubusercontent.com/92215878/212970393-f8e712a6-3b2c-4231-a1f4-3f80f072522c.png)

## Your Design
![image](https://user-images.githubusercontent.com/92215878/212970454-67741845-6d36-4290-8b5a-c9ab56f2c51a.png)

2023-01-17 17:42 UTC, jasonfelice commented on style.css
> +body {
- [ ] Please make sure the design is mobile responsive. Everything is retracting to the left when I reduce my screen size. Kindly fix that. 😸 

![image](https://user-images.githubusercontent.com/92215878/212970852-53c1baba-6074-4713-89cc-ee775096d68c.png)

2023-01-17 17:42 UTC, jasonfelice commented on index.html
> +            <div class="seeproject">
- [ ] Please adjust the style to make it look like the Figma template.

Figma Design
![image](https://user-images.githubusercontent.com/92215878/212971133-9fb1f657-41a2-4bfd-b247-d900808b742a.png)

Your Design
![image](https://user-images.githubusercontent.com/92215878/212971201-29dae6a0-804f-4c0e-9525-675842268a2b.png)

2023-01-17 17:42 UTC, jasonfelice commented on index.html
> +                    <img class="pic2" src="images/Frame 32.png" alt="">
- [ ] Kindly consider using text instead of images to make it look more appealing.

![image](https://user-images.githubusercontent.com/92215878/212971954-08cad351-d8ec-41c6-9f31-a92f2717dd16.png)

2023-01-17 17:42 UTC, jasonfelice commented on index.html
> +                <div class="form">
- [ ] Make sure, this section is perfectly centered like the Figma template.

![image](https://user-images.githubusercontent.com/92215878/212972342-762e0a5b-09d8-4e78-9110-06240673176b.png)

2023-01-17 17:42 UTC, jasonfelice commented on index.html
> +                    <img class="z" src="images/Container.png" alt="">
- [ ] Use input fields instead of images, as they will be later used to submit the data on the form. 😸

2023-01-19 15:47 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @mwakiogeofrey 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 15:47 UTC, iambenkis commented on index.html
> +        </header>
- [ ] As requested by the previous code reviewer, Kindly make sure you use the correct font for this logo :100: 

|  Your design | Figma design |
| :---: | :---: |
| ![212970454-67741845-6d36-4290-8b5a-c9ab56f2c51a (1)](https://user-images.githubusercontent.com/80458199/213484383-ca47b9bb-c68d-4fbd-8ffd-caaf7f8d6e68.png) | ![212970393-f8e712a6-3b2c-4231-a1f4-3f80f072522c](https://user-images.githubusercontent.com/80458199/213484761-f864686d-1c03-40e7-b5e6-d16fde131120.png) |

2023-01-19 15:47 UTC, iambenkis commented on index.html
> +                    <h1 class="four">A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard</h1>
- [ ] @mwakiogeofrey  , Make sure you follow the suggesting my fellow code review gave you, On this point, I should stick to figma design as requested, it means make sure the fonts, colors, margins, paddings, are the same 

| Your Design |  Figma design | 
|:---:| :---:|
| ![212971201-29dae6a0-804f-4c0e-9525-675842268a2b](https://user-images.githubusercontent.com/80458199/213486280-b05da14b-b3e7-48bd-bc0b-265711dea19d.png) | ![212971133-9fb1f657-41a2-4bfd-b247-d900808b742a](https://user-images.githubusercontent.com/80458199/213486352-69825fb5-a573-409d-8fec-b75b970ba51d.png)|

2023-01-19 15:47 UTC, iambenkis commented on index.html
> +            </div>
- [ ] [**OPTIONAL**] Kindly remove this form because it's not a part of the requirement, and it will be a part of the next milestone. Remember to stick to the design with this form though :+1:  

![212972342-762e0a5b-09d8-4e78-9110-06240673176b](https://user-images.githubusercontent.com/80458199/213487329-a1dbc362-bdb5-4b1e-ae14-7931912e6b7e.png)

2023-01-19 15:47 UTC, iambenkis commented on style.css
> +body {
- [ ]  Please make sure the design is mobile responsive. Everything is retracting to the left when I reduce my screen size. Kindly fix that by making sure Minimum mobile screen is 375px. And Errors in screen sizes less than 375px should be ignored :smile: 

![212970852-53c1baba-6074-4713-89cc-ee775096d68c](https://user-images.githubusercontent.com/80458199/213488186-e73ebe9f-4381-41c8-8110-76039dd8a0cf.png)

2023-01-20 16:58 UTC, RaoAkif approved these changes
## STATUS: APPROVED 🎉🎉🎉

Hi @mwakiogeofrey, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approve-image](https://ci5.googleusercontent.com/proxy/zq80mRZVpq-eAhdzmvNYP-LJmESV4U2mCLkUDj-J77H6FKB6oLO-eL8kGFENlnk15aQQPnJ2K7hSGZiaZBHMKFZEM6yCAT5H0leJxszpiJ_ZRxNc5L9uv6Wf0BFZUomZYiYN6ppiHgltD6qjc_Kh8RbH3b4nVLPghJlpfxM29IAi_q8djloxFmcQQ_I2iIY_rYXVUeBiSfNsVRfk0iq3wo75_nf9QHejNs5EwcDwp7n4vukAV0rFF6xBnAenIBlJ9_CuSGN37pZ0FDROc_LU_rInohwgD5sTJnITUxeXsq5juhu5btEu0AhtqpFV5MDVTQMfZw=s0-d-e1-ft#https://camo.githubusercontent.com/b4e8f035e0f2d20302034402026b8df675e3a9dd93b722d1b0a047112e68044d/68747470733a2f2f632e74656e6f722e636f6d2f4a52665739444c534f764141414141432f7365616c2d7365616c2d6f662d617070726f76616c2e676966)

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions
- You are using this complicated way of importing file.
![image](https://user-images.githubusercontent.com/61361037/213757788-587b25fa-cc61-4fda-88ba-7d2a996e7a44.png)
If you use `lower_case_with_underscores`, you won't find any difficulty in that.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 17:02 UTC, merged